name: Interchain Test Runner

on:
  workflow_call:
    inputs:
      test-matrix:
        type: string
        required: true
        description: "Path of the interchain test matrix file"

jobs:
  run_interchaintest:
    name: Interchain Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout public-awesome/stargaze # Need this to access the test matrix files
        uses: actions/checkout@v3
        with:
          sparse-checkout: ${{ inputs.test-matrix }}

      - name: Download interchaintest
        uses: actions/download-artifact@v4
        with:
          name: interchaintest

      - name: Download Stargaze Docker image
        uses: actions/download-artifact@v4
        with:
          name: sg
          path: /tmp

      - name: Make interchaintest binary executable
        run: chmod +x ./interchaintest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Load Stargaze Docker image
        run: docker load --input /tmp/sg.tar && docker images

      - name: Run interchaintest
        run: ./interchaintest -matrix ./${{ inputs.test-matrix }} -log-file stdout
